### ISSUE TITLE
能否添加npm支持？

### ISSUE THREAD

**Issue by Phinome** [zorro-html/zorro#1]
能否将项目放入npm repo ，现在大多数的企业内部都部署有私有的npm repo ，当一个项目执行初始化时，npm install 一步就能到位，因此，不知是否能将 zorro 添加到 npm repo 或者添加一个 npm package.json 。

**Comment by Jinjiang** [comment]
恩，主仓库的 `package.json` 会考虑加上，但前端静态资源现状越来越多使用 bower，它更加轻便同时符合前端的习惯，版本管理和发布也没有 npm 那么繁琐。目前可以通过 `bower install zorro` 来快速部署，依赖关系写在 `bower.json` 里，和 npm 类似。

**Comment by Phinome** [comment]
多谢～可能是我个人喜好的问题吧
